# Generated by Django 4.2.7 on 2023-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman_SD', models.CharField(blank=True, max_length=255, null=True)),
                ('chairman_board', models.CharField(blank=True, max_length=255, null=True)),
                ('board_members', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_accountant', models.CharField(blank=True, max_length=255, null=True)),
                ('orgbin', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('bank_license', models.CharField(blank=True, max_length=255, null=True)),
                ('custodian', models.CharField(blank=True, max_length=255, null=True)),
                ('major_participants', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_dealers', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_holdings', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOrganizationNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
